[package]
name = "emv_parser"
version = "0.1.1"
edition = "2021"
description = "An EMV Message Parser"
license = "MIT OR Apache-2.0"
repository = "https://github.com/HosseinAssaran/EMV-Parser"

[dependencies]
emv_tlv_parser = "0.1.5"
hex = "0.4.3"

[http]
http.check-revoke = "false"
